language: csharp
dist: trusty
mono: none
dotnet: 1.0.4

before_install:
- sudo apt-get -qq update
- sudo apt-get install -y libxml2-dev
# To support encryption of environment variable file, uncomment the following
# - openssl aes-256-cbc
#   -in serverless-environment-variables.yml.enc -out serverless-environment-variables.yml
#   -d
#   -k $ENCRYPTION_KEY

before_script:
- npm install -g serverless@1.23.0

script:
- "./build.sh --quiet verify"

branches:
  only:
  - master
  - prod

deploy:
- provider: script
  skip_cleanup: true
  script: "./deploy.sh"
  on:
    all_branches: true
    tags: false

env:
  global:
  - BUILD_VERSION: 0.0
